ATM-Consulting/dolibarr_module_of

admin/of_setup.php, class/ordre_fabrication_asset.class.php, langs/fr_FR/of.lang
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/5)
=> NEW concat hour for WS in OF

core/modules/modof.class.php, fiche_of.php, tpl/fiche_of.tpl.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/8)
=> New ajout d'un droit pour supprimer un of au statut "Terminé"

admin/of_setup.php, class/ordre_fabrication_asset.class.php, fiche_of.php, tpl/fiche_of.tpl.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/11)
=> Fix save on validate

fiche_of.php
Modifs demandées par Acropose mais qui me semblent généralisables
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/12)
=> New stock theo of

class/ordre_fabrication_asset.class.php, exempleTemplate/etiquette.html, exempleTemplate/etiquette_custom.html, fiche_of.php, langs/en_US/of.lang, langs/fr_FR/of.lang, liste_of.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/13)
=> Update traduction part 1

class/ordre_fabrication_asset.class.php, fiche_of.php, lib/of.lib.php, liste_of.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/14)
=> NEW link asset from order to OF

class/ordre_fabrication_asset.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/16)
=> Fix tva du prix fournisseur non reporté

fiche_of.php, tpl/fiche_of.tpl.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/20)
=> NEW quick edit field

liste_of.php
This reverts commit 01ac54014c83914a3951216b4204733299644796.
Better solution then  #18 with a pull of abricot
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/19)
=> Revert "FIX : GROUP BY strict"

class/ordre_fabrication_asset.class.php, core/modules/modof.class.php, fiche_of.php, langs/fr_FR/of.lang, liste_of.php
- merge from 1.0 (workstation, etc)
- new list to view supplier order linked to of waiting for reception
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/21)
=> New list supplier order

class/ordre_fabrication_asset.class.php, fiche_of.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/22)
=> fix details for pricing on OF

class/ordre_fabrication_asset.class.php, fiche_of.php, langs/fr_FR/of.lang, script/interface.php, tpl/fiche_of.tpl.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/23)
=> FIX change method to update needed qty by to make qty

admin/of_setup.php, class/ordre_fabrication_asset.class.php, core/triggers/interface_99_modof_oftrigger.class.php, langs/fr_FR/of.lang
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/24)
=> NEW allow of to follow supplier order manual linked status

class/ordre_fabrication_asset.class.php, fiche_of.php
- fix cost calcul for to_make product
- fix propagation to line needed of parent of
- fix aff
- fix creation child of isn't at good place
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/25)
=> fix of cost, of line parent

liste_of.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/28)
=> New print stock physique on order of tab

class/actions_of.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/29)
=> FIX : protection requête sql

class/ordre_fabrication_asset.class.php
Je n'utilise pas le stockage/destockage partiel
L'association avec mes assets et le destockage fonctionnent, par contre avant de terminer l'OF, si j'indique que j'ai consommé moins que prévu sur un NEEDED alors il faut restocker la différence mais cela ne marche pas
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/31)
=> Fix le restockage avec asset des needed ne fonctionne pas

class/ordre_fabrication_asset.class.php
Reverts ATM-Consulting/dolibarr_module_of#31
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/32)
=> Revert "Fix le restockage avec asset des needed ne fonctionne pas"

admin/of_setup.php, core/modules/modof.class.php, fiche_of.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/36)
=> Fix modèle odt déplacé dans "documents" + upload dans "documents"

admin/of_setup.php, core/modules/modof.class.php, fiche_of.php
+ Update ajout du tableau d'équipement pour l'impression du PDF OF
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/37)
=> Fix déplacement du template dans un sous dossier à OF

class/ordre_fabrication_asset.class.php, fiche_of.php, langs/fr_FR/of.lang
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/38)
=> Fix 1.0 message non explicite

liste_of.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/39)
=> Fix calcul cout prévu/réel

liste_of.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/40)
=> Merge master into 1.0

lib/of.lib.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/41)
=> Fix : stock theo doit prendre tous les statuts d'OF

class/ordre_fabrication_asset.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/42)
=> FIX cant finish billed supplier order

class/ordre_fabrication_asset.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/43)
=> Fix pmp line

class/ordre_fabrication_asset.class.php
parse line in all direction, not because it's fun, just because it's needed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/45)
=>  fix bug pmp to parent, and close of qty 

admin/of_setup.php, class/ordre_fabrication_asset.class.php, langs/fr_FR/of.lang, liste_of.php
and fix list cost values
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/46)
=> NEW use delay for purchase for task delay

class/ordre_fabrication_asset.class.php, core/triggers/interface_99_modof_oftrigger.class.php, fiche_of.php, liste_of.php, tpl/fiche_of.tpl.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/47)
=> fix acropose

class/ordre_fabrication_asset.class.php, core/modules/modof.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/48)
=> New allow to link needed to workstation on creation

admin/of_setup.php, class/ordre_fabrication_asset.class.php, langs/fr_FR/of.lang
Added conf to launch Child OF on virtual stock instead of real stock
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/50)
=> Add conf to launch ChildOF on virtual Stock

class/of_amount.class.php, class/ordre_fabrication_asset.class.php, core/modules/modof.class.php, langs/fr_FR/of.lang, liste_of.php, script/create-maj-base.php, script/fix/fix-pmp-for-product-from-of.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/52)
=> New of amounts

admin/of_setup.php, class/ordre_fabrication_asset.class.php, fiche_of.php, langs/fr_FR/of.lang, tpl/fiche_of.tpl.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/55)
=> New extrafields options

admin/of_setup.php, class/ordre_fabrication_asset.class.php, fiche_of.php, langs/en_US/of.lang, langs/fr_FR/of.lang, liste_of.php, tpl/fiche_of.tpl.php
- add dates start + end to stock data
- add worsktations into list + config to show or not
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/54)
=> New dates list info

class/ordre_fabrication_asset.class.php, langs/en_US/of.lang, langs/fr_FR/of.lang
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/57)
=> Fix mouvement de stock

admin/of_setup.php, core/triggers/interface_99_modof_oftrigger.class.php, langs/fr_FR/of.lang, lib/of.lib.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/58)
=> NEW close of when closing last task

class/ordre_fabrication_asset.class.php, core/modules/modof.class.php, fiche_of.php, langs/en_US/of.lang, langs/fr_FR/of.lang, tpl/fiche_of.tpl.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/61)
=> Fix logique d'utilisation de la colonne "Quantité utilisée"

fiche_of.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/62)
=> Fix édition d'un OF depuis une autre entité

class/ordre_fabrication_asset.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/63)
=> FIX : tk8228 : date start tâches en 1970

admin/of_setup.php, class/actions_of.class.php, class/ordre_fabrication_asset.class.php, config.default.php, create-asset-on-bill.php, fiche_of.php, index.php, liste_of.php, script/interface.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/66)
=>  FIX: handle asset renamed to assetatm

class/ordre_fabrication_asset.class.php, core/modules/modof.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/69)
=> FIX : suppression des tâches liées à un of malgré la parenté

admin/of_setup.php, core/modules/modof.class.php, fiche_of.php, langs/en_US/of.lang, langs/fr_FR/of.lang, tpl/fiche_of.tpl.php
Si conf different de vide alors affichage du poids + du mini tu1 qui est en fait le poids minal du produit
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/71)
=> New mini tu 1

admin/of_setup.php, exempleTemplate/etiquette_custom.html, langs/en_US/of.lang, langs/fr_FR/of.lang, liste_of.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_of/74)
=> NEW: copy order line desc to OF + display it on labels

admin/of_setup.php, class/ordre_fabrication_asset.class.php, fiche_of.php, langs/fr_FR/of.lang, liste_of.php, tpl/fiche_of.tpl.php
Ajout d'une notion de priorisation par jour sur les OF (ordre lié à un numéro)
Recalculer automatiquement l'ordre des OF par jour en cas de réorganisation de l'ordre d'un OF
Modification de l’ordre d’affichage des OF pour que ceux-ci s’affichent dans l’ordre de leur planification
=> New priorisation of

admin/of_setup.php, class/actions_of.class.php, class/ordre_fabrication_asset.class.php, core/modules/modof.class.php, core/triggers/interface_99_modof_oftrigger.class.php, langs/fr_FR/of.lang, script/interface.php
Amélioration  du module afin de permettre de rattacher plusieurs OF à un projet en  cumulant les temps des tâches de production à réaliser
PR lié : 
https://github.com/ATM-Consulting/dolibarr_module_tasklist/pull/7
https://github.com/ATM-Consulting/dolibarr_module_gantt/pull/10
=> New cumul task time if same workstation

admin/of_setup.php, class/ordre_fabrication_asset.class.php, fiche_of.php, langs/fr_FR/of.lang
Ajout de la création automatique d’une nouvelle tâche de traitement des non conforme lors de l'enregistrement d’un OF
=> New task if non compliant

admin/of_setup.php, class/ordre_fabrication_asset.class.php, core/triggers/interface_99_modof_oftrigger.class.php, fiche_of.php, langs/fr_FR/of.lang, lib/of.lib.php, liste_of.php, tpl/fiche_of.tpl.php
Possibilité de faire remonter les infos de la commande liée ligne à ligne plutôt que de l'attribut fk_commande (ouvre la possibilité de gérer une liaison commande-of N-N)
=> New manage link of line by line

langs/fr_FR/of.lang, liste_of.php
NEW : Pouvoir réordonner les rangs depuis la liste des OFs
=> NEW order rank on list

class/ordre_fabrication_asset.class.php, fiche_of.php, langs/fr_FR/of.lang, tpl/fiche_of.tpl.php
merge la branche 1.0 dans la master
conflit uniquement sur fiche_of.php
=> Merge 1 in master

class/ordre_fabrication_asset.class.php
Problème : le $this->rank est set avant la date de lancement mais fait des tests dessus.
La fonction "setDelaiLancement" qui permet de set cette date est appelée après le save (j'imagine pour éviter des problèmes sur le create), or dans cette fonction il y un test sur "status != DRAFT" donc pour moi aucun interet à que ce soit après le save
=> FIX delai set after save

langs/fr_FR/of.lang, liste_of.php
Nouveau filtre "tous sauf terminés" sur la liste des of
=> New filter all except closed on of list

admin/of_setup.php, class/actions_of.class.php, core/modules/modof.class.php, langs/fr_FR/of.lang, lib/of.lib.php
Add a column on orderlines in customer order card to display the OF linked to the line
=> New display of on commandlines

class/ordre_fabrication_asset.class.php, lib/of.lib.php
Ajouter des informations dans le tooltip d'un OF (status de l'OF et Date de besoin)
=> New retour add date status to of in command line

admin/of_setup.php, class/ordre_fabrication_asset.class.php, fiche_of.php, langs/fr_FR/of.lang
Correction d'une boucle infinie... lié à des configurations incompatibles
ajout d'une configuration de limitation en jour pour rendre les configurations compatibles.
=> Fix infinite loop and strange behaviors

admin/of_setup.php, class/actions_of.class.php
need https://github.com/ATM-Consulting/dolibarr_module_abricot/pull/110
fix issue https://github.com/ATM-Consulting/dolibarr_module_of/issues/91 too
=> Add abricot version checking

fiche_of.php
- FIX :  Étend la selection de tiers de type prospect/Client sur la fiche OF au lieu d'être limité aux clients.
=> FIX : select company filter TK11759

ChangeLog.md, admin/of_setup.php, class/ordre_fabrication_asset.class.php, core/modules/modof.class.php, langs/fr_FR/of.lang
NEW Option for revert task hierarchy
=> NEW : T2669 - Option for revert task hierarchy

ChangeLog.md, core/modules/modof.class.php, tpl/fiche_of.tpl.php
#FIX tkda020075 US translation
QtyToMake us translation
=> 1.15 fix tkda020075 trad us

ChangeLog.md, class/actions_of.class.php, core/modules/modof.class.php, tpl/fiche_of.tpl.php
Pull up de https://github.com/ATM-Consulting/dolibarr_module_of/pull/122
=> Main pull up 1.15 fix tkda020075 trad us

ChangeLog.md, admin/of_models.php, admin/of_setup.php, class/actions_of.class.php, class/ordre_fabrication_asset.class.php, core/modules/modof.class.php, core/modules/of/doc/pdf_ofexemple.modules.php, core/modules/of/modules_of.php, fiche_of.php, langs/fr_FR/of.lang, langs/fr_FR/ofpdf.lang, lib/of.lib.php
Ajoute la compatibilité avec la gestion classic des PDF par Dolibarr.
Ajoute une conf permettant de placer la colonne numéro de poste (extrafields ligne) en première colonne
=> NEW : std doc compatibility

ChangeLog.md, admin/of_models.php, admin/of_setup.php, class/actions_of.class.php, class/ordre_fabrication_asset.class.php, core/modules/modof.class.php, core/triggers/interface_99_modof_oftrigger.class.php, document.php, fiche_of.php, liste_of.php, script/fix/fix-pmp-for-product-from-of.php, script/interface.php, shipable_prev.php
cf. https://github.com/ATM-Consulting/dolibarr_module_of/pull/129
- NOTOKENRENEWAL
- NOCSRFCHECK
- GETPOST
- module descriptor
Note: some compatibility issues were not checked for (boxes, missing CSRF token in link URLs, triggers)
=> PULLUP: FIX: Dolibarr v13+v14 compatibility:

ChangeLog.md, admin/of_models.php, admin/of_setup.php, class/actions_of.class.php, class/ordre_fabrication_asset.class.php, core/modules/modof.class.php, core/triggers/interface_99_modof_oftrigger.class.php, document.php, fiche_of.php, liste_of.php, script/fix/fix-pmp-for-product-from-of.php, script/interface.php, shipable_prev.php
- NOTOKENRENEWAL
- NOCSRFCHECK
- GETPOST
- module descriptor
Note: some compatibility issues were not checked for (boxes, missing CSRF token in link URLs, triggers)
=> FIX: Dolibarr v13+v14 compatibility:

changeLog.md, class/ordre_fabrication_asset.class.php, core/modules/modof.class.php
Lorsqu'un OF est terminé, le numéro de lot des équipements créés est renseigné par la ref OF. Il ne créé plus de Num_lot vides.
=> FIX : fill lot number

ChangeLog.md, admin/of_setup.php, class/ordre_fabrication_asset.class.php, core/modules/modof.class.php, core/modules/of/doc/pdf_ofexemple.modules.php, core/triggers/interface_99_modof_oftrigger.class.php, fiche_of.php, langs/fr_FR/of.lang, liste_of.php, tpl/fiche_of.tpl.php
Attente merge de Workstation https://github.com/ATM-Consulting/dolibarr_module_workstation/pull/30
- NEW : Compatibility with Workstation ATM for Dolibarr v14 *28/06/2021* - 2.0.0  
**require WorkstationAtm 2.0**
=> NEW : Compatibility with Workstation ATM for Dolibarr v14

ChangeLog.md, core/modules/modof.class.php, fiche_of.php, tpl/fiche_of.tpl.php
Ajout du numéro de numéro de lot correspondant au numéro de série dans la colonne 'Lot' des produits nécessaires à la fabrication
=> FIX : Add lot numbers in lot column

ChangeLog.md, core/modules/modof.class.php, fiche_of.php, tpl/fiche_of.tpl.php
PR d'origine : https://github.com/ATM-Consulting/dolibarr_module_of/pull/140
=> PULLUP_2.2 FIX lotnumbers lot column

ChangeLog.md, class/actions_of.class.php, core/modules/modof.class.php, core/triggers/interface_99_modof_oftrigger.class.php, fiche_of.php, langs/en_US/of.lang, langs/fr_FR/of.lang, tpl/fiche_of.tpl.php
Sur un of, affichage d'un bouton "Transfert de stock" qui permet d'effectuer l'action sur les produits nécessaires de l'OF.
Conditions particulières : 
- Le bouton doit être visible seulement si le module "Transfert de stock" est activé
- Les lot / numero de série ne sont pas gérés
=> New t3149 stock transfert

ChangeLog.md, core/modules/modof.class.php, fiche_of.php, script/interface.php, tpl/fiche_of.tpl.php
Remplacer le select unique des équipements liés aux composants OF par un multiselect
Ne pas afficher les équipements avec un stock de 0 ou moins
Fix bug qui affiche l'équipement même si il est déjà lié au composant
=> NEW RD : multiselect asset of needed products

ChangeLog.md, core/modules/modof.class.php, fiche_of.php, script/interface.php, tpl/fiche_of.tpl.php
- Remplacer le select unique des équipements liés aux composants OF par un multiselect
- Ne pas afficher les équipements avec un stock de 0 ou moins
-  Fix bug qui affiche l'équipement même si il est déjà lié au composant
=> New rd multiselect asset of needed products

ChangeLog.md, core/modules/modof.class.php, core/triggers/interface_99_modof_oftrigger.class.php
Ajout du lien de l'OF lié au transfert de stock sur la card du transfert de stock
=> NEW : OF Link with stock transfer

ChangeLog.md, core/modules/modof.class.php, fiche_of.php, langs/en_US/of.lang, langs/fr_FR/of.lang, tpl/fiche_of.tpl.php
Dans le tableau des composants d'OF, permettre la modification en masse de l'entrepôt pour tous les produits d'un coup
=> New ret beaumont of massaction warehouse product needed

ChangeLog.md, class/ordre_fabrication_asset.class.php, core/modules/modof.class.php, liste_of.php
cf. https://github.com/ATM-Consulting/dolibarr_module_of/pull/145
=> PULLUP: Fix 2.4 include from workstationatm

ChangeLog.md, class/ordre_fabrication_asset.class.php, core/modules/modof.class.php
=> PULL-UP: Fix 2.7 fatal t objet std not found

core/triggers/interface_99_modof_oftrigger.class.php
Can't delete OF beacause there is link with stocktransfer
=> FIX : Can't delete OF beacause there is link with stocktransfer

core/triggers/interface_99_modof_oftrigger.class.php
PR d'origine : https://github.com/ATM-Consulting/dolibarr_module_of/pull/158
=> PULLUP Fix 2.8 need stock transfer

core/triggers/interface_99_modof_oftrigger.class.php, script/interface.php
PR d'origine : https://github.com/ATM-Consulting/dolibarr_module_of/pull/158
=> PULLUP Fix 2.9 need stock transfer

core/triggers/interface_99_modof_oftrigger.class.php, script/interface.php
PR d'origine : https://github.com/ATM-Consulting/dolibarr_module_of/pull/158
=> PULLUP Fix 2.10 need stock transfer

core/triggers/interface_99_modof_oftrigger.class.php, script/interface.php
PR d'origine : https://github.com/ATM-Consulting/dolibarr_module_of/pull/158
=> PULLUP Fix main need stock transfer

ChangeLog.md, core/modules/modof.class.php, script/interface.php
The click on the gear with a ToMake qty of zero now decreases the quantities of the needed products
=> FIX : Recalcul nomenclature quantities

ChangeLog.md, core/modules/modof.class.php, script/interface.php
PR d'origine : https://github.com/ATM-Consulting/dolibarr_module_of/pull/200
=> PULLUP Main : FIX recalcul nomenclature quantities

ChangeLog.md, core/modules/modof.class.php, tpl/fiche_of.tpl.php
Suppression du bouton modifier en vue de la refonte de la fiche OF
=> NEW : Remove modify button OF card

ChangeLog.md, class/ordre_fabrication_asset.class.php, core/modules/modof.class.php, liste_of.php
PULLUP : https://github.com/ATM-Consulting/dolibarr_module_of/pull/205
=> PULLUP : Amélioration de conf "Prix d'achat/revient suggéré par défaut" du module nomenclature

ChangeLog.md, class/ordre_fabrication_asset.class.php, core/modules/modof.class.php
=> fix DA021687

class/ordre_fabrication_asset.class.php, core/modules/modof.class.php, fiche_of.php
Branche 1.8 créé a partir de la version du client car la numérotation avec le systeme actuel a commencé à la V 1.14
Donc pas de changelog possible sinon ça va compliquer les choses.
Fix non reporté sur branche suivante non plus car pas nécessaire.
=> Fix pmp update on close with hidden conf OF_FORCE_SET_FOURNITURE_COST_PMP_ON_CLOSE

changeLog.md, class/ordre_fabrication_asset.class.php
=> PULLUP : 1.14 Fix pmp update on close with hidden conf OF_FORCE_SET_FOURNITURE_COST_PMP_ON_CLOSE

changeLog.md
=> PULLUP : 1.15 Fix pmp update on close with hidden conf OF_FORCE_SET_FOURNITURE_COST_PMP_ON_CLOSE

changeLog.md
=> PULLUP : 2.13 Fix pmp update on close with hidden conf OF_FORCE_SET_FOURNITURE_COST_PMP_ON_CLOSE

changeLog.md
=> PULLUP : MAIN Fix pmp update on close with hidden conf OF_FORCE_SET_FOURNITURE_COST_PMP_ON_CLOSE

ChangeLog.md, core/modules/modof.class.php, fiche_of.php
Pullup de https://github.com/ATM-Consulting/dolibarr_module_of/pull/257
=> Main pullup 2.14 fix compatibiliy stock transfer standard

ChangeLog.md, core/modules/modof.class.php, core/triggers/interface_99_modof_oftrigger.class.php
Pull up de la PR : https://github.com/ATM-Consulting/dolibarr_module_of/pull/261
=> PULLUP - Fix include stock transfert

ChangeLog.md, core/modules/modof.class.php, fiche_of.php, tpl/fiche_of.tpl.php
PULLUP [main] | FIX : DA023993 - Problème de focus
See : https://github.com/ATM-Consulting/dolibarr_module_of/pull/263
=> PULLUP [main] | FIX : DA023993 focus non fonctionnel

ChangeLogImMeca.md, class/ordre_fabrication_asset.class.php
Set du fk_entrepot lors de la création d'Of depuis une commande
=> FIX : DA024666 
